server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: Rhcf2306
    url: jdbc:postgresql://localhost:5432/users
    username: barbershop
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    show-sql: true
