server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: Leandrobhte7127
    url: jdbc:postgresql://db-barbearia.cihm4w9fopkb.us-east-1.rds.amazonaws.com:5432/db_barbearia
    username: leandrobhte
    #hikari:
      # maxLifeTime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: barbershoppuc@gmail.com
    password: cauppyhnzlijqpch

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
