server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: e0a5718e382145410c92c199d4566c8a4aeca7dfc8b4e7d827898fa45944bb92
    url: jdbc:postgresql://ec2-54-86-106-48.compute-1.amazonaws.com:5432/d16559kd8tnngo
    username: arjmaexwmfmynj
    #hikari:
      # maxLifeTime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: barbershoppuc@gmail.com
    password: rzswdtswjdikmsoj

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
